services:
  web:
    build:
      context: ./
      target: web
      args:
        FLAGS: -tls
    ports:
      - "8080:8080"
    volumes:
      - ./certificates:/opt/website/certificates
      - ./db:/opt/website/db
  test:
    build:
      context: ./
      target: test
    volumes:
      - ./certificates:/opt/website/certificates
      - ./db:/opt/website/db