services:
  web:
    build: .
    network_mode: host
    ports:
      - "8080:8080"
    volumes:
      - ./certificates:/opt/website/certificates
      - ./db:/opt/website/db
  test:
    build: .
    volumes:
      - ./certificates:/opt/website/certificates
      - ./db:/opt/website/db